language: php
php:
  - 5.3
  - 5.4
  - 5.5
env:
  - ZF_VERSION=v2.0.5
before_install:
  - php /home/travis/.phpenv/versions/5.3.27/bin/composer.phar self-update
  - php /home/travis/.phpenv/versions/5.4.24/bin/composer.phar self-update
  - php /home/travis/.phpenv/versions/5.5.9/bin/composer.phar self-update
